### ISSUE TITLE
TODO Backend: F11. Ask Question

### ISSUE THREAD

**Issue by wogur0602** [swsnu/swpp17-team6#14] opened 2017-11-10 11:56 UTC
1. Create Question model
  Question model includes
1-1. Author (UserInfo model, One to Many Relation)
1-2. Content (TextField)
1-3. Time (DateTimeField)
1-4. Related Service (Service model, Many to Many Relation)
1-5. Related Location (Location model / Many to Many Relation with Location L1/L2/L3 - discuss about policy)
1-6. Answers of this Question (Answer model, One to Many Relation)

2. Define API (api/question)
2-1. POST: Create my question
2-2. GET: Get my questions

(Optional)

3. Define API (api/question/latest)
3-1. GET: Get latest questions

4. Definie Api (api/question/related)
4-1. GET: Get questions are related with user's tag

5. Define Api (api/question/search)
5-1. GET: Get questions have searching keyword patterns

Exception Handling
1. other HTTP request => 405 not allowed
2. unsigned in => 401 unauthorized

**Comment by HS-YN** [comment] 2017-11-17 06:35
Would `api/question/<question_id>` that handles specific question by its id be needed?

**Comment by HS-YN** [comment] 2017-11-17 07:28
Also,
1-7 UserPushed (UserInfo model, many to many relationship)

6. Define API :  `api/question/pushed`
6-1. GET: Get questions that are pushed to me.
need to be defined.

**Comment by HS-YN** [comment] 2017-11-17 07:30
Another problem that is derived from the suggestion above is (this is actually for sprint 4),
When I post new question, how will the UserPushed data be updated?

**Comment by HS-YN** [comment] 2017-11-19 20:39
It is possible to check out implementation [here](https://github.com/swsnu/swpp17-team6/commit/1a9a16860c1c904c55a2ab00edeb138c4b866fc2).
  
Some technical difficulties are marked as `TODO` inside the code, so please take a look, especially `question_search()` and `question_related()`.

**Comment by wogur0602** [comment] 2017-11-24 08:20
Resolved in this Commit 0af54bb7f29c83eb762c86da0cffa89284fa4327 / 0f8cec330103057dd135f07e39d1dc627334d14d
Please review the Code. Thank you

**Comment by HS-YN** [comment] 2017-11-24 08:33
Finished reviewing. Since there is no problem with this commit and the issue is resolved, I will close this issue alongside with #15 .

**Closed** 2017-11-24 08:34 UTC
Labels: backend, Implemented, Reviewed, TODO
