### ISSUE TITLE
TODO Backend: F12. Answer Questions

### ISSUE THREAD

**Issue by wogur0602** [swsnu/swpp17-team6#15] opened 2017-11-10 12:03 UTC
1. Create Answer model
  Answer model includes
1-1. Author (UserInfo model, One to Many Relation)
1-2. Content (TextField)
1-3. Time (DateTimeField)
1-4. Question of this Answer (Question model, One to Many Relation)

2. Define API (api/answer)
2-1. GET: Get my questions

3. Define Api (api/<question_id>/answer)
2-1. GET: Get answers of question has id as <question_id>
2-2. POST: Create answer to question has id as <question_id>

Exception Handling
1. other HTTP request => 405 not allowed
2. unsigned in => 401 unauthorized

**Comment by wogur0602** [comment] 2017-11-24 08:20
Resolved in this Commit 0af54bb7f29c83eb762c86da0cffa89284fa4327 / 0f8cec330103057dd135f07e39d1dc627334d14d
Please review the Code. Thank you

**Comment by HS-YN** [comment] 2017-11-24 08:33
Finished reviewing. Since there is no problem with this commit and the issue is resolved, I will close this issue.

**Closed** 2017-11-24 08:34 UTC
Labels: backend, Implemented, Reviewed, TODO
